#spring mail
mail:
   smtp:
      username: 850912828@qq.com
      password: abcdefg
      smtpServer: smtp.qq.com
      port: 465
      fromMailAddress: 850124828@qq.com
      auth: true
      timeout: 1000

server:
   port: 60011
   servlet:
      contextPath: /wheel
cors.allow.origin: '*'
isLog:
   write: true
   read: false
# 跨域访问
mybatis:
   configLocation: mybatis-config.xml
#是否记录日志到数据库
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/wheel?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&serverTimezone=GMT%2B8
      username: root
#MyBatis配置文件地址
      password: 850934828
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
# 打印sql
#logging:
# level:
#   com.zee.dao.unity: DEBUG
      filters: stat
# MySQL config
      maxActive: 80 #最大活动连接
      initialSize: 10 #初始化连接
      maxIdle: 60 #最大空闲连接
#本地环境
      minIdle: 10 #最小空闲连接
      maxWait: 3000 #从池中取连接的最大等待时间，单位ms
      validationQuery: SELECT 1 #验证使用的SQL语句
      testWhileIdle: true #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testOnBorrow: false #拿出连接时不要测试，否则很影响性能
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      timeBetweenEvictionRunsMillis: 30000 #每30秒运行一次空闲连接回收器
      minEvictableIdleTimeMillis: 1800000 #池中的连接空闲30分钟后被回收
      numTestsPerEvictionRun: 3 #在每次空闲连接回收器线程(如果有)运行时检查的连接数量
   thymeleaf.cache: false
   freemarker.cache: false
   velocity.cache: false
   groovy.template.cache: false
   mvc:
      favicon:
         enabled: false
   multipart:
      enabled: true
      max-file-size: 1000mb
      max-request-size: 1000mb
   jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      joda-date-time-format: yyyy-MM-dd HH:mm:ss

      
mongo:
   address: 192.168.200.39
   port: 27017
   maxConnect: 50
   maxWaitThread: 100
   maxTimeOut: 300
   maxWaitTime: 300
   database: mango
   collection: DaIotMonitorData
upload:
   diskPath: D:\ProgramData\ApplicationResource\Wheel
   linkPath: http://localhost/resource
   swfPath: http://localhost:8081/resource/swf/flvplayer.swf
mangoTaskSwitch:
   sentimentTask: false
   ecTask: false
# mongoProperties
   wholesaleTask: false
   
# ===== 自带swagger配置 ===== #
springfox:
  documentation:
    # 生产环境时关闭ui
    swagger-ui:
      enabled: false
    #  生产环境时关闭自动启动扫描注解
    auto-startup: false
    
# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: mango
  application-version: 1.0
  application-description: 整合springfox swagger 3.0
  try-host: http://localhost:${server.port}